apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: toolkit-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
spec:
  entrypoint: full
  serviceAccountName: workflow
  arguments:
    parameters:
    - name: release
      value: "1.0.1"
    - name: container_image
      value: vfarcic/devops-toolkit
    - name: repo
      value: git://github.com/vfarcic/argo-workflows-vs-tekton-demo
  volumes:
  - name: kaniko-secret
    secret:
      secretName: regcred
      items:
        - key: .dockerconfigjson
          path: config.json
  templates:
  - name: full
    dag:
      tasks:
      - name: build-container-image
        templateRef:
          name: container-image
          template: build-kaniko-git
          clusterScope: true
        arguments:
          parameters:
          - name: app_repo
            value: "{{workflow.parameters.repo}}"
          - name: container_image
            value: "{{workflow.parameters.container_image}}"
          - name: container_tag
            value: "{{workflow.parameters.release}}"
      - name: deploy-staging
        templateRef:
          name: deploy
          template: kustomize
          clusterScope: true
        arguments:
          parameters:
          - name: container_image
            value: "{{workflow.parameters.container_image}}"
          - name: container_tag
            value: "{{workflow.parameters.release}}"
          - name: manifests_path
            value: kustomize/overlays/staging
          - name: app_repo
            value: "{{workflow.parameters.repo}}"
        dependencies:
        - build-container-image
      - name: integration-tests
        templateRef:
          name: random
          template: echo
          clusterScope: true
        arguments:
          parameters:
          - name: message
            value: Running integration tests
        dependencies:
        - deploy-staging
      - name: functional-tests
        templateRef:
          name: random
          template: echo
          clusterScope: true
        arguments:
          parameters:
          - name: message
            value: Running functional tests...
        dependencies:
        - deploy-staging
      - name: deploy-production
        templateRef:
          name: deploy
          template: kustomize
          clusterScope: true
        arguments:
          parameters:
          - name: container_image
            value: "{{workflow.parameters.container_image}}"
          - name: container_tag
            value: "{{workflow.parameters.release}}"
          - name: manifests_path
            value: kustomize/overlays/production
          - name: app_repo
            value: "{{workflow.parameters.repo}}"
        dependencies:
        - integration-tests
        - functional-tests
